version: "2.3"
services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    volumes:
      - ~/faceReId/db/rabbitmq:/var/lib/rabbitmq
    expose:
      - "5672"
    ports:
      - "15672:15672"
      - "5672:5672"

  redis:
    image: redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ~/faceReId/db/redis:/data
    expose:
      - "6379"
    ports:
      - "6379:6379"

  mongodb:
    image: mongo
    restart: unless-stopped
    volumes:
      - ~/faceReId/db/mongo:/data/db
    expose:
      - "27017"
    ports:
      - "27017:27017"

  face_reid:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: unless-stopped
    volumes:
      - ~/faceReId/driveData:/video
      - ~/faceReId/faces:/faces
      - ~/faceReId/db/faiss:/faiss
    depends_on:
      - mongodb
      - rabbitmq
      - redis
    links:
      - mongodb
      - rabbitmq
      - redis

networks:
  default: