version: "2.3"
services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    volumes:
      - ~/Desktop/db_faceReId/rabbitmq:/var/lib/rabbitmq
    expose:
      - "5672"
    ports:
      - "15672:15672"
      - "5672:5672"

  redis:
    image: redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ~/Desktop/db_faceReId/redis:/data
    expose:
      - "6379"
    ports:
      - "6379:6379"

  mongodb:
    image: mongo
    restart: unless-stopped
    volumes:
      - ~/Desktop/db_faceReId/mongo:/data/db
    expose:
      - "27017"
    ports:
      - "27017:27017"

  face_reid:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: unless-stopped
    volumes:
      - ~/Desktop/driveData:/video_data
      - ~/Desktop/db_faceReId/faiss:/faiss
    depends_on:
      - mongodb
      - rabbitmq
      - redis
    links:
      - mongodb
      - rabbitmq
      - redis

volumes:
  rabbitmq-data:
  mongodb-data:
  redis-data:

networks:
  default: